Math Magician: milestone 2
Sevenpros/maths_magician pull request #2
Opened 2022-08-03 17:16 UTC by Sevenpros

##  Math Magician: milestone 2 Add components
in this PR we 👍 
- Added calculator component
- Update README.md

2022-08-03 17:35 UTC, arslanbisharat requested changes
Hi @Sevenpros, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The Pull Request has a proper title and description. ✔️
- You have added a descriptive Readme file. Good Job. ✔️
- There is no linter error is present. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please make sure you right descriptive comments. Commenting involves placing Human Readable Descriptions inside of computer programs detailing what the Code is doing. Proper use of commenting can make code maintenance much easier, as well as helping make finding bugs faster. Further, commenting is very important when writing functions that other people will use. :x:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 17:35 UTC, arslanbisharat commented on src/calc.css
> +  justify-content: end !important;
- [ ] Maintaining a site that has !important scattered throughout is a nightmare. If you feel like you need to use !important, what that says to me is that you need to brush up on your [CSS specificity](http://coding.smashingmagazine.com/2007/07/27/css-specificity-things-you-should-know/).

2022-08-03 17:35 UTC, arslanbisharat commented on src/components/calculator.js
> +export default class Calculator extends React.PureComponent {
- [ ] The Calculator.js component should be class-base.

2022-08-03 17:35 UTC, arslanbisharat commented on src/App.js
> +          Edit
- [ ] The Calculator.js component should be class-based

2022-08-03 17:35 UTC, arslanbisharat commented on src/App.js
> +          {' '}
- [ ] The `App.js`(main component) should have the imported `Calculator.js` component

2022-08-04 21:43 UTC, andersonlebon approved these changes
## Hi @Sevenpros  


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-04 21:43 UTC, andersonlebon commented on src/components/calculator.js
> +  // eslint-disable-next-line class-methods-use-this
## [OPTIONAL]
- [ ] Kindly solve linters instead of disabling them as they help you structure well your code and prevent future bugs.

2022-08-04 21:59 UTC, merged